sudo: required
addons:
  addons: 
  chrome: beta
  apt:
    packages:
    - chromium-chromedriver
language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- export PATH=$PATH:/usr/lib/chromium-browser/
#- "./node_modules/ionic/bin/ionic serve --no-open &"
#- sleep 30
install:
- npm i
- npm install -g cordova ionic
- node scripts/patch-webpack.js
script:
# - npm run e2e
#- npm run test
- node scripts/ci-set-build-number.js
- ionic build --engine=browser --prod
notifications:
  pushover:
    api_key:
      secure: FpOyalFnM1J5wCO+3eWmhrO4OCMLwscYV9eEfh1LZUVZBrQPi1Jy6rW1f5O3Xa+tB6dVJM45sGDXTnh50QMIxfP/k/9Hyy3LtGct8YR7r/BtQpZ9MpfhIsXF0rhbMrNw1CGk4n3uNyqI0zwuvQfzVwqtV7cQiqPxUsOJ0v24gm0+o2jAg+AgSOzhzA78+/tJgM4g+bzq/u7lcu/kN+Ij1X2WUmRVkNkSsHg2b1dHAPV0FCWK+eTEJ/y9/19Hh8mv7oxXdp9rrlHCphTADm1jDVy6Xk4c/og5bxm++mLZsA7JlPyda70jsKGPuaHTQR5hPR7ma1WP8pkJ35iQRbUsxeDTHMUpMUfeZWFPmnX7Va9y5aI0AlS4AUJeHBzkEy53MorvK+A6xLPz+2IcOf8U3cBYtjdFFAAEUDzOuX4uMPzHlIVRzsiBk+miaqm7kEsAOj5TPh5P9NezqpMCforYgfupXUgj9A2r2Lq3GhU3x4ZlrGbaSe5aIYynUiWZoosZbuRHVhIeUZR8iV4AseAGXV0fkng4k+YV1RxmHkAe1UfmUw7R2IREf4BZlxCcKUKXqz7vdOHmE5PhVoPzCb92M/9Tgxvb4uUE0B6RLGpMwIKgivSSL1jn2PYDzk6FqLPcAJArKAZytIFem34S2jmzT3x0jpa8HspM27kr4lLGpww=
    users:
      secure: se2uFseEvvMwpbWRHx2A5A3ekeP3uJ25KEAL57Io/wZgCVKuk8XXinyNTAbGxib0ipvED7S80YFmO7S0yaBaLJDcSJtEdnGcDn8gBnFmftU2il2ovGpfxv/Xp50CSYcqizGs16x+2LcdtZBG1hdICf2wEJQXvhObD7B6XjVgkKinICgr1ZZeUxNBBU1hyfsP5V/goAsqrIC7TFicmcSgJYWl6N906ZYZ20YOkziHqfpt6FeLwk2C4YpxEFYIaDJLtgqTttXQ8owph77FnvuA21Mo8W/e8MvyLJ5Hq10KH3h5vAuIFnCM/xkhvDoHSVA5V96g4567K7xy37Aa4OsyMV/dhTDku0Ik65cWWvgSflc1arDYsiiQKOku5IXYqy0rTU/0ouMuINqdUidSjwLy5765QTIUhrff1vSAdcpiyfLPceoQapzudcEgnwGF9BqzHTHv5c570MwyJn/BzZpy2iGqm6RfVmbyBeweR1rx/0OxQkeHvncgMZY7uZLtI0A6eSlJq5m1VyrRYlel4bc4erWI0swulvXDWzkuUGhQxTVhYx5G+G2xnbAXeS0Eb/jWCXQiQrp64JKGYvNiQM0+ayel60Y5wmWFYdH9PLhlZHOfuS8mkzLAo3aQuU9inwZ0YxYhk7XVPKQ5R9bjfeW4gmSIIOYVzuNHK8k8V+0DX0Y=
deploy:
- provider: firebase
  token:
    secure: nC+svlPf8GJMMGcnUQLRsXxEP0CWZkSKCJySj/Tpws6wFfE37CgtL3WQB2D0EKWs1yCIobaMOU9qfr4XWqQh+aN/nbpJ5iNaKYGSxPZyJOz+rbVp2pa4j4/yhcdaTysAXGlUOiHM3ZhgoDkYB3vxoZRPhcKolc9dXqcl3JM7iwSxUA7INrQcuNbReVE8sJwZbK0oEKTjgQEPcqI1QsFijar0oLcxa4DYd6+doSNR978RjhSPns1bu8xmPTmz3oT/9NQm86QdQXA5kA6C/N11uG2aBN9Sz/SX90sYb0bOyqLrfirMt8SEs/YCLxZXS2yxrK3iSkdF1VVAZbyLHBM1FW7kF3HB41LGUbgHDm9PD9PgkeOJpRS7b31RvATkc6enYklvN1b04N80OvTgvoDpV5YA53vG2VAJPBRTWtcdtAijwN0Yxs9ChCuKG+OaT3AA6SRM+2IZ83KKNqXRkXMf1ZGJZjZyqnl4lfa2SLkzwNfhk85KPFTiHVrWKnFrOshoG83vEikjOSKdYawR+j0PL2BQfiKX4UF7HHi6zVSVLnXFK7hmJ3YyX1zCpsgskjoUAPJYBc5yfWqPSjHFLpLWUtl/Ep12IHLK48SEjj29oR8QlpG1Marbg+AAAfWMqywEO0g7FHYhdrurOybbu0Le+zW0N440ABKY7C+1nzh2aNs=
  project: myetpwallet-app
  skip_cleanup: true
  on:
    branch: master
- provider: firebase
  token:
    secure: nC+svlPf8GJMMGcnUQLRsXxEP0CWZkSKCJySj/Tpws6wFfE37CgtL3WQB2D0EKWs1yCIobaMOU9qfr4XWqQh+aN/nbpJ5iNaKYGSxPZyJOz+rbVp2pa4j4/yhcdaTysAXGlUOiHM3ZhgoDkYB3vxoZRPhcKolc9dXqcl3JM7iwSxUA7INrQcuNbReVE8sJwZbK0oEKTjgQEPcqI1QsFijar0oLcxa4DYd6+doSNR978RjhSPns1bu8xmPTmz3oT/9NQm86QdQXA5kA6C/N11uG2aBN9Sz/SX90sYb0bOyqLrfirMt8SEs/YCLxZXS2yxrK3iSkdF1VVAZbyLHBM1FW7kF3HB41LGUbgHDm9PD9PgkeOJpRS7b31RvATkc6enYklvN1b04N80OvTgvoDpV5YA53vG2VAJPBRTWtcdtAijwN0Yxs9ChCuKG+OaT3AA6SRM+2IZ83KKNqXRkXMf1ZGJZjZyqnl4lfa2SLkzwNfhk85KPFTiHVrWKnFrOshoG83vEikjOSKdYawR+j0PL2BQfiKX4UF7HHi6zVSVLnXFK7hmJ3YyX1zCpsgskjoUAPJYBc5yfWqPSjHFLpLWUtl/Ep12IHLK48SEjj29oR8QlpG1Marbg+AAAfWMqywEO0g7FHYhdrurOybbu0Le+zW0N440ABKY7C+1nzh2aNs=
  project: myetpwallet-testnet
  skip_cleanup: true
  on:
    branch: testnet
- provider: firebase
  token:
    secure: C2LxR9Wyqj94B8OYokOTpML8yx++3GL7rfbdrtaxO752z0BbfosYyzESJBaEiXLmTybB77o7l+tAXigqorFJ+2TWUfwkLHT6w1eb92FwYkl7G0eTMvzZSWqXT/6cRajXmw/cHYctrtktB48ff0WwhP0+F7IXGGtUKD/y2wHbdKZkW8o5aKbZzSB1aeFDvCchmu0B6ohgme6ZAp0kej/dlz6LHQG2p5yGEVaqiagj5u9X7ABB7/pe/4JrkDZzWzSeL4V4l3iOhzgw3C14ntwCQdenQ5LqoEiz/WSi0UmXh3v8kmsu4m+SbdIfS588d16efg0ScVx5rho233K/HPr1M8OaEeedGjpBAH1x8rUSSk4LGXMBtMsuMzEcNqgeFekzZwoc/1F5PVgdtHkcP2BY/uzA+tAs1+CGPaKjVexypmq/GYa4wPjVI1mWCeCH+C11EuNCO8/jt0O3cctRfcG5j5LUJGEgkJIa4ZZJNSCupSU/7+kmCzEIjXBWouVIqszL+ZArXOOPqymTicFf0egz62i6hsyXk9eOSKATCwBeNvOPZgEJZcOBwWlz96z44N+BWxqQvE0JmNrVFU8yt0SNg4R9ePAchXRNdXAwJ7MrwVvW0mpXkYM19fH8NjPuwoHcp3Gy4h2qgd4PjW/15zNuxb5zIHKcoSqh6ew9XyaJWwQ=
  project: myetpwallet-dev
  skip_cleanup: true
  on:
    branch: dev
